version: '3.9'
services:
  db:
    container_name: sql_server_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Password12!
      - ACCEPT_EULA=Y